import { getTranslations } from "next-intl/server";
import { PageIntro } from "@/components/site/sections/PageIntro";
import { Prose } from "@/components/site/ui/Prose";
import { Section } from "@/components/site/ui/Section";
import {
  getLegalDocument,
  type LegalDocument as LegalDocumentType,
} from "@/features/legal/queries";

type LegalDocumentProps = {
  doc: LegalDocumentType;
  title: string;
};

/** Page title plus the server-rendered iubenda document (or a placeholder). */
export async function LegalDocument({ doc, title }: LegalDocumentProps) {
  const [html, t] = await Promise.all([
    getLegalDocument(doc),
    getTranslations("Legal"),
  ]);

  return (
    <>
      <PageIntro title={title} />
      <Section>
        {html ? (
          // Trusted source: HTML generated by our own iubenda account.
          <Prose html={html} />
        ) : (
          <p className="text-muted-foreground">{t("unavailable")}</p>
        )}
      </Section>
    </>
  );
}
