import { getTranslations } from "next-intl/server";
import {
  getLegalDocument,
  type LegalDocument as LegalDocumentType,
} from "@/features/legal/queries";

type LegalDocumentProps = {
  doc: LegalDocumentType;
  title: string;
};

/** Page title plus the server-rendered iubenda document (or a placeholder). */
export async function LegalDocument({ doc, title }: LegalDocumentProps) {
  const [html, t] = await Promise.all([
    getLegalDocument(doc),
    getTranslations("Legal"),
  ]);

  return (
    <>
      <h1>{title}</h1>
      {html ? (
        // Trusted source: HTML generated by our own iubenda account.
        <div dangerouslySetInnerHTML={{ __html: html }} />
      ) : (
        <p>{t("unavailable")}</p>
      )}
    </>
  );
}
